### ISSUE TITLE
App does not reload Settings after restart

### ISSUE THREAD

**Issue by CaseyJNova** [fred-dev/ps3EyeSyphon_2#4]
I was trying to get the app to load without the Auto Corrections. Also, to load flipped.

When I use the app, change the settings, and click the save button it will reload properly when I hit the refresh button. However, if I load the program fresh it does not remember these settings. I checked the files in "data" and made sure they were correct. However, it always loads in the defaults the app ships with.

Have you noticed this as well?

I am keeping the app inside the folder it ship with, no rename, next to the data folder. Does it NEED to live in Applications? On the Desktop?

**Comment by fred-dev** [comment]
All should be good from the last update.
